### PR TITLE
Adding Support for Unity, GNOME, XFCE, and MATE

### PR DESCRIPTION
**Pull request by 3goliad**
Resolving issue #1 by adding basic support for several other desktop environments. Tested on latest Ubuntu, Xubuntu, Ubuntu-MATE. Not tested on any prior versions, WMs, GNOME environments, or in crontab.

### CODE REVIEW

**Review by KarthikNayak — COMMENTED** [review]
'Readme' you mean?

**Comment by KarthikNayak** [comment]
Looks good to me, thanks! I'm thinking of removing autoconf, for a simpler Makefile. What do you think.

**Comment by duck2** [comment]
This is actually very nice- remarkable how you tested it with several environments and past versions of them :beer:

**Comment by KarthikNayak** [comment]
Merged! Thanks :+1:

**Pull request merged**
